spring:
  application:
    name: HotelBooking

  datasource:
    url: jdbc:postgresql://localhost:5435/hotel_booking_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ****
    password: ****
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

secret:
    jwt:
      string: b2Lg1fPqs92hJ3nT1VpXw!Gz0zPb3kXv7YvX@jJs9R8tT0h8K9V5e8b2v!hC


stripe:
  api:
    public_key: ****
    secret_key: ****
