version: "3.8"
services:
  postgresql:
    container_name: hotel_booking
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: hotel_booking_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - hotel-net
    restart: unless-stopped


networks:
  hotel-net:
    driver: bridge

volumes:
  postgres: